### ISSUE TITLE
感谢开源  在本地开发环境中尝试启动失败 能指导一下吗

### ISSUE THREAD

**Issue by sw586** [shijie1991/highker#1]
的配置修改为以下内容，以适应本地开发环境：

URL_SCHEME=http://
ROOT_DOMAIN="highker.local"
API_DOMAIN="api.${ROOT_DOMAIN}"
ADMIN_DOMAIN="admin.${ROOT_DOMAIN}"
CDN_DOMAIN="cdn.${ROOT_DOMAIN}"

然后，hosts 文件中：

127.0.0.1 highker.local
127.0.0.1 api.highker.local
127.0.0.1 admin.highker.local
127.0.0.1 cdn.highker.local

highker-www目录下

php artisan serve --host=highker.local --port=80 
php artisan serve --host=api.highker.local --port=8001 
php artisan serve --host=admin.highker.local --port=8002 
php artisan serve --host=cdn.highker.local --port=8003 

这样的姿势对吗？还是必须在正式环境中才能运行。

**Comment by shijie1991** [comment]
www 目录是 laravel 项目目录

**Comment by shijie1991** [comment]
这个项目是 采用包扩展模式开发的

在 www 目录下 执行 

php artisan highker:instal
